import { PageIntro } from '@/components/PageIntro'
import { useLocale } from '@/i18n/locale'

export function MethodologyPage() {
  const locale = useLocale()
  const sections = locale === 'tr' ? [
    ['Uyumluluk durumları', '“Doğrulandı” durumu yalnızca tam cihaz + çalıştırma ortamı + model + kuantizasyon ölçümüyle verilir. “Sığıyor” bellek ve çalıştırma ortamı kanıtına, “Kısıtlı” açık bir sınıra, “Desteklenmiyor” hesaplanan veya ölçülen uyumsuzluğa, “Bilinmiyor” ise kanıt yokluğuna işaret eder.'],
    ['Bellek hesabı', 'Gereksinim = gerçek model paketi boyutu + KV önbelleği × eşzamanlılık + çalıştırma ortamı ek yükü. Ek yük ölçülmediyse azami(2 GiB, ağırlıkların %10’u); kullanılabilir bellek doğrulanmadıysa toplam belleğin %80’i uygulanır.'],
    ['Uygunluk puanı', 'Bu puan ölçülmüş performans veya başarı olasılığı değildir. Katalog iş yükü puanları %40 + kullanılabilir bellek kapasitesi %25 + çalıştırma ortamı listesinin varlığı %20 + gürültü tercihi %10 + fiyat kaydı durumu %5. Bellek bileşeni 96 GiB’da 100’e ulaşır; çalıştırma ortamı listesi doluysa 88 kullanılır. Puan belirli bir modelin bağlam hızını, işletim sistemi uyumluluğunu veya bant genişliğini ölçmez.'],
    ['Paket optimizasyonu', 'Önce kompakt biçim, doğrulanmış sistem güç sınırı, çevrimdışı model eşleşmesi ve yerel fiyat/vergi koşulları uygulanır. Üç ekosistemden biri karşılanamıyorsa INELIGIBLE sonucu verilir. Uygun paketler içinde önce bütçe, ardından kapsam, en düşük uygunluk, sezgisel puan/maliyet oranı ve maliyet değerlendirilir; bütçeye sığmayan hedef fazlara ayrılır. Gürültü bir tercihtir. Altyapı maliyeti toplama dahil değildir.'],
    ['Fiyat ve vergi', 'TR ve DE gözlemleri KDV durumunu, US gözlemleri satış vergisi hariç tabanı açıkça gösterir. Döviz dönüşümü yerel fiyatın yerine geçmez ve vergi tabanları tek en-ucuz listesinde karıştırılmaz.'],
    ['Hata durumunda güvenli veri', 'Yenileme elle başlatılır ve seçilmiş veri girdisini doğrular; kaynakları indirmez veya yeniden doğrulamaz. Şema ve yayınlama hatasında son sağlam anlık görüntü korunur. Aynı kayıt ve yapılandırmada %35 üzeri fiyat değişimi karantinaya alınır. Lisans, dosya özeti ve erişim değişiklikleri ayrıca kaynak incelemesi gerektirir.'],
    ['Tarih, birim ve varsayımlar', 'Katalog derleme tarihi, kaynak doğrulama tarihi değildir. Kaynak durumları son anlık görüntüye aittir. Eski ve referans fiyatlar kendi tarihleriyle tahminde kullanılabilir. Bellek hesapları GiB, bant genişliği GB/s, metin üretimi tokens/s kullanır; üreticilerin GB ve TOPS etiketleri ayrı okunmalıdır. TOPS, token hızına dönüştürülmez.'],
    ['Paylaşım ve öğrenme sistemi', 'Senaryo URL’si girdileri taşır; sonuç, puan veya katalog sürümünü sabitlemez. Aynı girdiler aynı katalog ve hesaplamayla aynı sonucu verir. Altyapı tercihleri kaydedilir ancak maliyet veya puana eklenmez. aserdargun.com bağlantıları öğrenme rotalarıdır; diğer uygulamalara otomatik senaryo aktarımı yoktur.'],
  ] : [
    ['Compatibility states', 'verified requires an exact device + runtime + model + quant measurement. fits uses memory and runtime evidence, constrained names an explicit limit, unsupported records a calculated or measured mismatch, and unknown means evidence is absent.'],
    ['Memory calculation', 'Requirement = actual artifact size + KV cache × concurrency + runtime overhead. When overhead is unmeasured use max(2 GiB, 10% of weights); when usable memory is unverified use 80% of total memory.'],
    ['Fit score', 'This heuristic is not measured performance or a probability of success. Catalog workload scores 40% + usable-memory capacity 25% + presence of a runtime list 20% + noise preference 10% + price-record status 5%. The memory component reaches 100 at 96 GiB; a non-empty runtime list contributes 88. The score does not measure model-specific context throughput, OS compatibility, or bandwidth.'],
    ['Package optimization', 'Compact form, verified system power limits, offline model matches, and local price/tax conditions are applied first. Missing an ecosystem produces INELIGIBLE. Eligible packages are ranked by budget, coverage, weakest fit, heuristic score/cost ratio, and cost; over-budget targets are phased. Noise is a preference. Infrastructure costs are excluded.'],
    ['Price and tax', 'TR and DE observations disclose VAT; US observations exclude sales tax. Currency conversion never replaces local price and tax bases are not mixed in one cheapest ranking.'],
    ['Fail-closed data', 'Refresh is manual and validates curated inputs; it does not fetch or reverify sources. Schema and publication failure preserve the last-known-good snapshot. Price moves above 35% for the same record and configuration are quarantined. License, hash, and access changes require separate source review.'],
    ['Dates, units, and assumptions', 'The catalog build date is not a source-verification date. Source states describe the accepted snapshot. Stale and reference prices may be used as dated estimates. Memory calculations use GiB, bandwidth GB/s, and text generation tokens/s; read manufacturer GB and TOPS labels separately. TOPS is not converted to token throughput.'],
    ['Sharing and the learning system', 'Scenario URLs carry inputs; they do not freeze results, scores, or catalog versions. The same inputs yield the same result with the same catalog and calculation. Infrastructure choices are recorded but do not affect cost or score. aserdargun.com links are learning paths; there is no automatic scenario transfer to other apps.'],
  ]
  return <>
    <PageIntro eyebrow={locale === 'tr' ? 'Açık karar sözleşmesi' : 'Open decision contract'} title={locale === 'tr' ? 'Metodoloji' : 'Methodology'} description={locale === 'tr' ? 'Bir önerinin nasıl üretildiği ve hangi koşulda geri çekildiği denetlenebilir.' : 'How a recommendation is produced—and when it is withdrawn—is auditable.'} />
    <div className="method-ledger">{sections.map(([title, body], index) => <section key={title}><span>0{index + 1}</span><div><h2>{title}</h2><p>{body}</p></div></section>)}</div>
    <section className="download-band"><div><p className="eyebrow">{locale === 'tr' ? 'VERİ / V1' : 'DATA / V1'}</p><h2>{locale === 'tr' ? 'Statik sözleşmeyi indir' : 'Download the static contract'}</h2></div><div><a href="/data/v1/catalog.json" download>catalog.json</a><a href="/manifest.json" download>manifest.json</a><a href="/changes.json" download>changes.json</a></div></section>
  </>
}
